exports.seed = function(knex, Promise) {
	return knex("Vote").del().then(function() {
		return knex("Vote").insert([
			{ user_id: 1, component_id: 1, vote: 1 },
			{ user_id: 1, component_id: 2, vote: -1 },
			{ user_id: 1, component_id: 3, vote: -1 },
			{ user_id: 1, component_id: 4, vote: 1 },
			{ user_id: 2, component_id: 1, vote: 1 },
			{ user_id: 2, component_id: 2, vote: 1 },
			{ user_id: 2, component_id: 3, vote: -1 },
			{ user_id: 2, component_id: 4, vote: 1 },
			{ user_id: 3, component_id: 1, vote: -1 },
			{ user_id: 3, component_id: 2, vote: -1 },
			{ user_id: 3, component_id: 3, vote: 1 },
			{ user_id: 3, component_id: 4, vote: 1 },
			{ user_id: 4, component_id: 1, vote: 1 },
			{ user_id: 4, component_id: 2, vote: 1 },
			{ user_id: 4, component_id: 3, vote: 1 },
			{ user_id: 4, component_id: 4, vote: 1 },

			{ user_id: 1, component_id: 5, vote: 1 },
			{ user_id: 1, component_id: 6, vote: 1 },
			{ user_id: 1, component_id: 7, vote: 1 },
			{ user_id: 2, component_id: 6, vote: 1 },
			{ user_id: 2, component_id: 7, vote: 1 },
			{ user_id: 2, component_id: 8, vote: 1 },
			{ user_id: 3, component_id: 5, vote: -1 },
			{ user_id: 3, component_id: 6, vote: -1 },
			{ user_id: 3, component_id: 8, vote: 1 },
			{ user_id: 4, component_id: 5, vote: 1 },
			{ user_id: 4, component_id: 7, vote: 1 },
			{ user_id: 4, component_id: 8, vote: 1 },
			{ user_id: 5, component_id: 5, vote: 1 },
			{ user_id: 5, component_id: 6, vote: 1 },
			{ user_id: 5, component_id: 8, vote: 1 },

			{ user_id: 1, component_id: 9, vote: 1 },
			{ user_id: 1, component_id: 10, vote: -1 },
			{ user_id: 1, component_id: 11, vote: -1 },
			{ user_id: 1, component_id: 12, vote: 1 },
			{ user_id: 2, component_id: 9, vote: 1 },
			{ user_id: 2, component_id: 10, vote: 1 },
			{ user_id: 2, component_id: 11, vote: -1 },
			{ user_id: 2, component_id: 12, vote: 1 },
			{ user_id: 3, component_id: 9, vote: -1 },
			{ user_id: 3, component_id: 10 vote: -1 },
			{ user_id: 3, component_id: 11, vote: 1 },
			{ user_id: 3, component_id: 12, vote: 1 },
			{ user_id: 4, component_id: 9, vote: 1 },
			{ user_id: 4, component_id: 10, vote: 1 },
			{ user_id: 4, component_id: 11, vote: 1 },
			{ user_id: 4, component_id: 12, vote: 1 },

			{ user_id: 1, component_id: 13, vote: 1 },
			{ user_id: 1, component_id: 14, vote: 1 },
			{ user_id: 1, component_id: 15, vote: 1 },
			{ user_id: 2, component_id: 13, vote: 1 },
			{ user_id: 2, component_id: 14, vote: 1 },
			{ user_id: 2, component_id: 15, vote: 1 },
			{ user_id: 3, component_id: 16, vote: -1 },
			{ user_id: 3, component_id: 17, vote: -1 },
			{ user_id: 3, component_id: 18, vote: 1 },
			{ user_id: 4, component_id: 16, vote: 1 },
			{ user_id: 4, component_id: 17, vote: 1 },
			{ user_id: 4, component_id: 18, vote: 1 },
			{ user_id: 5, component_id: 18, vote: 1 },
			{ user_id: 5, component_id: 19, vote: 1 },
			{ user_id: 5, component_id: 20, vote: 1 },
		]);
	});
};
