exports.seed = function(knex, Promise) {
	return knex("Fan").del().then(function() {
		return knex("Fan").insert([
			{ user_id: 1, component_id: 1 },
			{ user_id: 2, component_id: 2 },
			{ user_id: 1, component_id: 2 },
			{ user_id: 5, component_id: 3 },
			{ user_id: 4, component_id: 4 },
			{ user_id: 1, component_id: 5 },
			{ user_id: 3, component_id: 6 },
			{ user_id: 2, component_id: 6 },
			{ user_id: 1, component_id: 7 },
			{ user_id: 2, component_id: 7 },
			{ user_id: 3, component_id: 8 },
			{ user_id: 1, component_id: 8 },
			{ user_id: 2, component_id: 8 },
			{ user_id: 4, component_id: 8 },
			{ user_id: 5, component_id: 8 },
			{ user_id: 2, component_id: 9 },
			{ user_id: 3, component_id: 10 },
			{ user_id: 4, component_id: 10 },
			{ user_id: 5, component_id: 11 },
			{ user_id: 4, component_id: 12 },
			{ user_id: 5, component_id: 13 },
			{ user_id: 3, component_id: 14 },
			{ user_id: 1, component_id: 14 },
			{ user_id: 2, component_id: 14 },
			{ user_id: 5, component_id: 15 },
			{ user_id: 2, component_id: 16 },
			{ user_id: 1, component_id: 16 },
			{ user_id: 3, component_id: 16 },
			{ user_id: 4, component_id: 16 },
			{ user_id: 4, component_id: 17 },
			{ user_id: 1, component_id: 18 },
			{ user_id: 3, component_id: 19 },
			{ user_id: 1, component_id: 20 },
			{ user_id: 2, component_id: 20 },
			{ user_id: 3, component_id: 20 },
			{ user_id: 4, component_id: 20 },
			{ user_id: 5, component_id: 20 },
		]);
	});
};
